/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.oscvev.virtualchoir;

import de.oscvev.virtualchoir.core.VirtualChoirLookup;
import de.oscvev.virtualchoir.nodefactories.VirtualChoirsNodeFactory;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.ActionMap;
import javax.swing.text.DefaultEditorKit;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.filesystems.FileObject;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.nodes.Node;
import org.openide.nodes.NodeEvent;
import org.openide.nodes.NodeListener;
import org.openide.nodes.NodeMemberEvent;
import org.openide.nodes.NodeReorderEvent;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//de.oscvev.virtualchoir//FileExplorerView//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "FileExplorerViewTopComponent",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "de.oscvev.virtualchoir.FileExplorerViewTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_FileExplorerViewAction",
        preferredID = "FileExplorerViewTopComponent"
)
public final class FileExplorerViewTopComponent extends TopComponent implements ExplorerManager.Provider, PropertyChangeListener {

    private final ExplorerManager manager = new ExplorerManager();
    private AbstractNode rootNode;

    private static FileExplorerViewTopComponent instance;

    public FileExplorerViewTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(FileExplorerViewTopComponent.class, "CTL_FileExplorerViewTopComponent"));
        setToolTipText(NbBundle.getMessage(FileExplorerViewTopComponent.class, "HINT_FileExplorerViewTopComponent"));
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);

        ActionMap map = getActionMap();
        map.put(DefaultEditorKit.copyAction, ExplorerUtils.actionCopy(manager)); // currently unused
        map.put(DefaultEditorKit.cutAction, ExplorerUtils.actionCut(manager));
        map.put(DefaultEditorKit.pasteAction, ExplorerUtils.actionPaste(manager));

        associateLookup(ExplorerUtils.createLookup(manager, getActionMap()));
        initTree();
        VirtualChoirLookup.getDefault().addPropertyChangeListener(this);
        instance = this;

    }

    public static FileExplorerViewTopComponent getInstance() {
        return instance;
    }

    private void initTree() {
        rootNode = new AbstractNode(Children.create(new VirtualChoirsNodeFactory(), true));
        if (VirtualChoirLookup.getDefault().getFileObject() != null) {
            rootNode.setDisplayName(VirtualChoirLookup.getDefault().getFileObject().getNameExt());
        }
        rootNode.addNodeListener(new MainNodeExpander());
        rootNode.setIconBaseWithExtension("de/oscvev/virtualchoir/fileexplorer/resources/eLamX-File-Logo.png");
        manager.setRootContext(rootNode);

        manager.addPropertyChangeListener(new PropertyChangeListener() {

            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if (evt.getPropertyName().equals(ExplorerManager.PROP_SELECTED_NODES)) {
                    // hier können änderungen eingefügt werden
                }
            }
        });

    }

    public void expandNode(Node n) {
        beanTreeView.expandNode(n);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        beanTreeView = new org.openide.explorer.view.BeanTreeView();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(beanTreeView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(beanTreeView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.BeanTreeView beanTreeView;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return manager;
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals(VirtualChoirLookup.PROP_FILEOBJECT)) {
            FileObject fo = VirtualChoirLookup.getDefault().getFileObject();
            if (fo != null) {
                rootNode.setDisplayName(fo.getNameExt());
                beanTreeView.setRootVisible(true);
            } else {
                beanTreeView.setRootVisible(false);
            }
        }
    }
    
    private class MainNodeExpander implements NodeListener {

        @Override
        public void propertyChange(PropertyChangeEvent evt) {
        }

        @Override
        public void childrenAdded(NodeMemberEvent ev) {
            if (rootNode == null) {
                return;
            }
            for (Node n : rootNode.getChildren().getNodes()) {
                beanTreeView.expandNode(n);
            }
        }

        @Override
        public void childrenRemoved(NodeMemberEvent ev) {
        }

        @Override
        public void childrenReordered(NodeReorderEvent ev) {
        }

        @Override
        public void nodeDestroyed(NodeEvent ev) {
        }

    }
}
